name: publish
on:
    push:
        branches:
            - main
jobs:
    publish:
        permissions:
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{secrets.NPM_TOKEN}}
                  access: public
                  provenance: true
